const Event = {
  /* 收到新消息 */
  MESSAGE_RECEIVED: 'MESSAGE_RECEIVED',
  /* 会话列表更新 */
  CONVERSATION_LIST_UPDATED: 'CONVERSATION_LIST_UPDATED',
  /* 健康体检更新 */
  HEALTH_CHECK_UPDATE: 'HEALTH_CHECK_UPDATE',
  /* 顶部消息提醒 */
  MESSAGE_NOTICE: 'MESSAGE_NOTICE',
  /* 音视频:会话邀请 */
  VIDEO_CHAT_CREATE: 'VIDEO_CHAT_CREATE',
  /* 音视频:会话邀请 */
  VIDEO_CHAT_INVITE_HANDLER: 'VIDEO_CHAT_INVITE_HANDLER',
  /* 音视频:取消会话 */
  VIDEO_CHAT_CANCEL_HANDLER: 'VIDEO_CHAT_CANCEL_HANDLER',
  /* 音视频:超时取消 */
  VIDEO_CHAT_TIMEOUT_CANCEL_HANDLER: 'VIDEO_CHAT_TIMEOUT_CANCEL_HANDLER',
  /* 音视频:挂断 */
  VIDEO_CHAT_HANGUP_HANDLER: 'VIDEO_CHAT_HANGUP_HANDLER',
  /* 音视频:拒绝 */
  VIDEO_CHAT_REJECT_HANDLER: 'VIDEO_CHAT_REJECT_HANDLER',
  /* 音视频:超时拒绝 */
  VIDEO_CHAT_TIMEOUT_REJECT_HANDLER: 'VIDEO_CHAT_TIMEOUT_REJECT_HANDLER',
  /* 音视频:音视频切换 */
  VIDEO_CHAT_SWITCH_HANDLER: 'VIDEO_CHAT_SWITCH_HANDLER',
  /* 音视频:进房 */
  VIDEO_CHAT_ENTER_ROOM_HANDLER: 'VIDEO_CHAT_ENTER_ROOM_HANDLER',
  /* 音视频:新增成员 */
  VIDEO_CHAT_ADD_MEMBER_HANDLER: 'VIDEO_CHAT_ADD_MEMBER_HANDLER',
};

export default Event;
